apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-oap
  namespace: tangming
  labels:
    app: skywalking-oap
    version: v8.7.0-es6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-oap
      version: v8.7.0-es6
  template:
    metadata:
      labels:
        app: skywalking-oap
        version: v8.7.0-es6
    spec:
      containers:
      - name: skywalking-oap
        image: 172.22.50.227/system_containers/apache/skywalking-oap-server:8.7.0-es6
        imagePullPolicy: IfNotPresent  #默认值,本地有则使用本地镜像,不拉取
        ports:
        - containerPort: 11800
          name: grpc
        - containerPort: 12800
          name: restful
        env:
        - name: SW_STORAGE  #指定存储介质为 elasticsearch
          value: elasticsearch 
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: elasticsearch:9200
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-oap
  namespace: tangming
  labels:
    app: skywalking-oap
    version: v8.7.0-es6
spec:
  type: NodePort
  ports:
    - port: 12800
      name: restful
    - port: 11800
      name: grpc
  selector:
    app: skywalking-oap