apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-ui
  namespace: tangming
  labels:
    app: skywalking-ui
    version: v8.7.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-ui
      version: v8.7.0
  template:
    metadata:
      labels:
        app: skywalking-ui
        version: v8.7.0
    spec:
      containers:
      - name: skywalking-ui
        image: 172.22.50.227/system_containers/apache/skywalking-ui:8.7.0
        imagePullPolicy: IfNotPresent  #默认值,本地有则使用本地镜像,不拉取
        ports:
        - containerPort: 8080
          name: page
        env:
        - name: SW_OAP_ADDRESS
          value: skywalking-oap:12800
          #value: http://10.110.8.113:12800
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-ui
  namespace: tangming
  labels:
    app: skywalking-ui
    version: v8.7.0
spec:
  type: NodePort
  ports:
    - port: 8080        # k8s集群内服务访问端口 
      targetport: 8080  # 容器端口 
      nodePort: 8080    # 外部流量访问k8s集群service入口的一种方式（另一种方式是LoadBalaner）
      name: page
  selector:
    app: skywalking-ui